---

- name: install fail2ban
  apt:
    name: fail2ban
    state: latest

- name: configure fail2ban
  template:
    src: fail2ban_jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0755"
  notify:
    - restart fail2ban