---
- name: install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
    state: latest

- name: template /etc/apt/apt.conf.d/20auto-upgrades
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: enable automatic reboots for configured servers
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^Unattended-Upgrade::Automatic-Reboot'
    line: 'Unattended-Upgrade::Automatic-Reboot "true";'
  when: harden_allow_unattended_update_reboots is defined and harden_allow_unattended_update_reboots == "true"
